#!/bin/zsh

CUCKOO=$(ls -1 ~/Library/Developer/Xcode/DerivedData/SwiftEthel-*/SourcePackages/checkouts/Cuckoo/run)
PROJECT_NAME="Ethel"

echo "CUCKOO: $CUCKOO"

generate() {
    for inputFile in $@; do
        typeset outDir="${inputFile:s/Sources\/Ethel/Tests\/EthelTests\/Mocks/:h}"
        
        # make sure we have target dir
        test -d $outDir || mkdir -p $outDir

        # generate mocks
        ${CUCKOO} generate --download --no-header --testable "${PROJECT_NAME}" --output "${outDir}/Mock${inputFile:t}" ${inputFile}
    done
}

generate $@

